
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GradProjectV5.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Member
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Member()
    {

        this.BeneficierMedicineRequests = new HashSet<BeneficierMedicineRequest>();

        this.BeneficierMedicineRequests1 = new HashSet<BeneficierMedicineRequest>();

        this.Consults = new HashSet<Consult>();

        this.ConsultAnswers = new HashSet<ConsultAnswer>();

        this.Doctors = new HashSet<Doctor>();

        this.Pharamacies = new HashSet<Pharamacy>();

    }


    public int ID { get; set; }

    public string FullName { get; set; }

    public string NationalId { get; set; }

    public string PhoneNo { get; set; }

    public Nullable<int> CityId { get; set; }

    public string Address { get; set; }

    public Nullable<int> GenderId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string UserId { get; set; }

    public string Age { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BeneficierMedicineRequest> BeneficierMedicineRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BeneficierMedicineRequest> BeneficierMedicineRequests1 { get; set; }

    public virtual City City { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Consult> Consults { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConsultAnswer> ConsultAnswers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Doctor> Doctors { get; set; }

    public virtual Gender Gender { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pharamacy> Pharamacies { get; set; }

}

}
